version: '3'
services:
  ursho:
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - app_postgres
  app_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'shortener'
    ports:
      - 5432:5432